- name: configure systemd for electricbook
  template: >
    src=systemd.electricbook.conf.j2
    dest=/lib/systemd/system/electricbook.service
  become: yes
  notify: 'restart electricbook'

- name: enable electricbook for systemd
  become: yes
  systemd: 
    name: electricbook
    daemon_reload: yes
    enabled: yes
    state: started
    masked: no
  notify: 'restart electricbook'
